### ISSUE TITLE
StickyList does not work with Hot Reload or StatefulWidgets

### ISSUE THREAD

**Issue by ctrinh98** [itsJoKr/sticky_header_list#1]
I just discovered this really great package and I've been using it tons! Unfortunately, I found out today that anything wrapped in a StickyList Widget will not be affected by hot reload or any state change in StatefulWidgets, which is a huge issue! Is there any fix available for this?

**Comment by itsJoKr** [comment]
Hi. It looks like my delegate class was part of State, and the state would persist on hot reloads. I moved the delegate out of state.

Can you please bump version to 1.0.3 and check if hot reload works for you.

**Comment by ctrinh98** [comment]
It works perfectly now! Thanks so much for the quick response and fix! :D
