### ISSUE TITLE
Better libs?

### ISSUE THREAD

**Issue by viniciussalvati** [itsJoKr/sticky_header_list#13]
In your deprecation notice, you mentioned there are better libs. Could you point us to them? Every lib I tried would not use a ListView (bad for performance) or use a Column inside the list view (also bad for performance).

I've hit the bug in #12 and was thinking about finding another library or fixing this one. Could you tell us what library you mentioned to be better than this one?

**Comment by itsJoKr** [comment]
Hey. I've used this one and it worked great for me: https://pub.dev/packages/sticky_headers

You would need to use Column for `content` inside `StickyHeader` if you want multiple rows under same header. I see you pointed that could be an issue, I don't think it would be an issue unless you have ton of items under the same header.

If that is your specific case you could use this other library where the delegate builds rows: https://pub.dev/packages/flutter_sticky_header
I've never used it and it looks more complex than the first one, so I would suggest giving a try to the first library.

**Comment by viniciussalvati** [comment]
Sorry for taking this long to answer.

What I'm doing is showing a list of contacts, with categories, and some of our clients have a few thousand contacts, so it could be a problem for them, especially memory usage (List view works perfectly). But we have some categories for the contacts, and I wanted a sticky header, so I thought to use your lib. I managed to get it to work with the second option you showed me, but it was a little more work.

Thanks for your help.
