### ISSUE TITLE
Using Refresh indicator when child not enough to scrollable

### ISSUE THREAD

**Issue by rickyazhari** [itsJoKr/sticky_header_list#2]
I've figure out when child not enough to trigger scrolling in list view, i can't swipe up to trigger on refresh from refresh indicator widget.

 i just play around in sticky_header_list.dart file and add attribute physics AlwaysScrollableScrollPhysics  in listview.builder seems working

**Comment by itsJoKr** [comment]
Merged. Thanks for the contribution.
