### ISSUE TITLE
Reverse the list order?

### ISSUE THREAD

**Issue by auggernaut** [itsJoKr/sticky_header_list#4]
Great package, almost exactly what I need.

I'm building a Chat app, however, so the list scrolls the opposite way from your example. I've tried adding `reverse: true` to the ListView.builder on line 76 of sticky_header_list.dart... which does invert the list, but then the header behavior gets wonky.

Any help is much appreciated!

**Comment by itsJoKr** [comment]
Since others may need this, I have implemented reverse option.

Please check 1.0.5 version. You can now set `reverse: true` as a parameter to `StickyList`.
